### ISSUE TITLE
Fix the OpenAPI schema for requests when creating a device

### ISSUE THREAD

**Issue by Fumiya-Tahara** [Fumiya-Tahara/uecs-navi#60]
## 概要
デバイス作成時にリクエストパラメータとしてHouseIDを受け取っていたものを、リクエストボディに全て含めるように変更する。

## 修正箇所
openapi/openapi.yml
internal/controller/openapi.gen.go(自動生成)

## 使用コマンド
openapiディレクトリ内で
```
oapi-codegen --config=config.yml openapi.yml
```
## やること

- openapiファイルのデバイス作成のパス、スキーマを変更する
- requestを受け取るようのスキーマも忘れずに

## やらないこと

-

**Comment by sug-1210** [comment]
追加事項
- パラメータからHouseIDは削除するがエンドポイントには残す
- openapiにsetpointの追加
- バリデーションの関係から自動生成は使わない
- バリデーションの構造体はcontroller/dto.goに記述
- #53 でバインドする構造体が変わるため変更しなかったhandler.goについてもdevice_nameを追加する
